### ISSUE TITLE
beet camp `fetchart` source not working

### ISSUE THREAD

**Issue by dchesbro** [snejus/beetcamp#50]
I've been trying to get the bandcamp `fetchart` source working, but so far have been unsuccessful. I'm running beets version 1.6.1 in the Linuxserver Docker container with Python version 3.10.12. I'm using the latest version of this plugin.

I have the following options set for `beetcamp`:

```
bandcamp:
  art: yes
  search_max: 4
```

And the following options set for `fetchart`:

```
fetchart:
  auto: yes
  cover_format: JPEG
  deinterlace: yes
  enforce_ratio: yes
  high_resolution: yes
  minwidth: 1000
  maxwidth: 1000
  sources: itunes filesystem
```

I also added the plugin as `bandcamp` under the `plugins` option. Searching and returning release details is working as expected, but so far no artwork has ever been returned when choosing a bandcamp candidate, even when visiting the release URL shows artwork is available. 

I've also tried adding entires to the `sources` option under `fetchart` -- I've tried `beetcamp`, `bandcamp`, and `Bandcamp`.

Some examples of release URLs that aren't returning artwork:

- ~~https://crumbtheband.bandcamp.com/album/jinx~~ **Edit:** At least this example was discarded because of the `enforce_ratio` setting above
- https://silentstreet.bandcamp.com/album/i-cant-stand-it-here-on-quiet-nights-singles-1981-82

If there is anywhere I can look for log details, I am happy to check and report back, or provide any other details of my config file. It's also possible I am misunderstanding how this feature is supposed to work, in which case some clarification would be greatly appreciated.
